# Generated by Django 4.1 on 2022-09-10 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_home', '0001_initial'),
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterdata',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.flat'),
        ),
        migrations.AddField(
            model_name='counterdata',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house'),
        ),
        migrations.AddField(
            model_name='counterdata',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.section'),
        ),
        migrations.AddField(
            model_name='counterdata',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_home.service'),
        ),
    ]
