# Generated by Django 4.1 on 2022-09-18 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_home', '0003_alter_service_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm_home.unit'),
        ),
    ]
