# Generated by Django 4.1 on 2022-09-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_home', '0004_alter_service_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(default='Test', error_messages={'required': 'Это поле обязательно к заполнению и не может быть пустым.'}, max_length=100),
        ),
    ]
