# Generated by Django 4.1 on 2022-09-19 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_home', '0006_alter_tariff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_home.service'),
        ),
    ]
