# Generated by Django 4.1 on 2022-09-19 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_home', '0008_alter_tariffservice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffservice',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_home.tariff'),
        ),
    ]
