# Generated by Django 4.1 on 2022-10-10 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_home', '0010_alter_counterdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterdata',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
