# Generated by Django 4.1 on 2022-10-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_home', '0011_alter_counterdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterdata',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
