# Generated by Django 4.1 on 2022-10-10 13:31

import crm_home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_home', '0013_alter_counterdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterdata',
            name='number',
            field=models.CharField(default=crm_home.models.get_next_counter_number, max_length=20, unique=True),
        ),
    ]
