# Generated by Django 4.1 on 2022-09-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='application',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='cashbox',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='flat',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='house',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='invoice',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='message',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='meter',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='owner',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='personal_account',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='requisites',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='service',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='site_management',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='statistics',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='tariff',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='users',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
