# Generated by Django 4.1 on 2022-09-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_role_application_alter_role_cashbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='father_name',
            field=models.CharField(blank=True, help_text='Отчество', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that UserID already exists'}, help_text='Required', max_length=100, null=True, unique=True, verbose_name='User ID'),
        ),
    ]
