# Generated by Django 4.1 on 2022-09-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_father_name_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Активен', 'Активен'), ('Новый', 'Новый'), ('Отключен', 'Отключен')], default='Новый', max_length=20),
        ),
    ]
