# Generated by Django 4.1 on 2022-09-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'Пользователь с таким ID уже существует.'}, help_text='Required', max_length=100, null=True, unique=True, verbose_name='User ID'),
        ),
    ]
