# Generated by Django 4.1 on 2022-09-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='viber',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
