# Generated by Django 4.1 on 2022-10-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_telegram_alter_customuser_viber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('Активен', 'Активен'), ('Новый', 'Новый'), ('Отключен', 'Отключен')], default='Новый', max_length=20, null=True),
        ),
    ]
