# Generated by Django 4.1 on 2022-10-11 12:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='request',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='request',
            name='type_master',
            field=models.CharField(choices=[('Сантехник', 'Сантехник'), ('Электрик', 'Электрик'), ('Слесарь', 'Слесарь'), ('Любой специалист', 'Любой специалист')], default='Сантехник', max_length=50),
        ),
    ]
