# Generated by Django 4.1 on 2022-10-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_request_date_alter_request_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('', 'Выберите...'), ('Новое', 'Новое'), ('В работе', 'В работе'), ('Выполнено', 'Выполнено')], default='Новое', max_length=50),
        ),
    ]
