# Generated by Django 4.1 on 2022-10-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0014_alter_flat_personal_account'),
        ('users', '0017_request_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_address_flat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='houses.flat'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_address_floor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.floor'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_address_house_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.house'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_address_section_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.section'),
        ),
    ]
