# Generated by Django 4.1 on 2022-10-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_messageusers_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(default='no income', max_length=100),
            preserve_default=False,
        ),
    ]
