# Generated by Django 4.1 on 2022-10-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_message_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageusers',
            name='read',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
