# Generated by Django 4.1 on 2022-10-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_messageusers_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageusers',
            name='read',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
