# Generated by Django 4.1 on 2022-11-09 20:14

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_customuser_username_alter_request_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.IntegerField(blank=True, default=users.models.get_next_user_id, error_messages={'unique': 'Пользователь с таким ID уже существует.'}, help_text='Required', null=True, unique=True, verbose_name='User ID'),
        ),
    ]
