version: '3.8'

services:
  db:
    image: postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  web:
    build: ./
#    command: python /usr/src/home24-main/manage.py runserver 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/home24-main/
    ports:
      - 8000:8000
    env_file:
      - ./.env
#    entrypoint: /usr/src/app/entrypoint.sh
#    depends_on:
#      - db
volumes:
  postgres_data: