# Generated by Django 4.1 on 2022-09-10 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_accounting', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0001_initial'),
        ('crm_home', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flat',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.floor'),
        ),
        migrations.AddField(
            model_name='flat',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house'),
        ),
        migrations.AddField(
            model_name='flat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flat',
            name='personal_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account_flat', to='crm_accounting.personalaccount'),
        ),
        migrations.AddField(
            model_name='flat',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.section'),
        ),
        migrations.AddField(
            model_name='flat',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_home.tariff'),
        ),
    ]
