# Generated by Django 4.1 on 2022-09-25 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='house',
            name='section',
        ),
        migrations.AddField(
            model_name='floor',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.house'),
        ),
        migrations.AddField(
            model_name='section',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.house'),
        ),
    ]
