# Generated by Django 4.1 on 2022-09-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_alter_house_address_alter_house_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='house/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='house/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='house/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='house/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='house/'),
        ),
    ]
