# Generated by Django 4.1 on 2022-09-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_alter_house_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
