# Generated by Django 4.1 on 2022-09-29 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounting', '0006_alter_personalaccount_account_number'),
        ('houses', '0007_alter_floor_title_alter_section_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='personal_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_flat', to='crm_accounting.personalaccount'),
        ),
    ]
