# Generated by Django 4.1 on 2022-09-30 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_alter_flat_personal_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='personal_account',
        ),
    ]
