# Generated by Django 4.1 on 2022-09-30 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounting', '0007_personalaccount_flat'),
        ('houses', '0009_remove_flat_personal_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='personal_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_flat', to='crm_accounting.personalaccount'),
        ),
    ]
