# Generated by Django 4.1 on 2022-09-30 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_flat_personal_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='section',
            field=models.ForeignKey(error_messages={'required': 'Это поле обязательно.'}, on_delete=django.db.models.deletion.CASCADE, to='houses.section'),
        ),
    ]
