# Generated by Django 4.1 on 2022-09-30 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_home', '0009_alter_tariffservice_tariff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0012_alter_flat_personal_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.floor'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flat',
            name='section',
            field=models.ForeignKey(blank=True, error_messages={'required': 'Это поле обязательно.'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.section'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm_home.tariff'),
        ),
    ]
