# Generated by Django 4.1 on 2022-09-10 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/about/')),
                ('additional_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('additional_header', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Страница о нас',
                'verbose_name_plural': 'Страницы О нас',
            },
        ),
        migrations.CreateModel(
            name='AboutService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/about_service/')),
            ],
            options={
                'verbose_name': 'Страница о сервисе',
                'verbose_name_plural': 'Страницы о сервисе',
            },
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desctiption', models.TextField(blank=True, max_length=1000, null=True)),
                ('key_words', models.TextField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Сео блок',
                'verbose_name_plural': 'Сео блоки',
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.seo')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.aboutservice')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1000)),
                ('slide1', models.ImageField(blank=True, null=True, upload_to='content/main')),
                ('slide2', models.ImageField(blank=True, null=True, upload_to='content/main')),
                ('slide3', models.ImageField(blank=True, null=True, upload_to='content/main')),
                ('apps_links', models.BooleanField(null=True)),
                ('seo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='content.seo')),
            ],
            options={
                'verbose_name': 'Главная',
                'verbose_name_plural': 'Главные',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/gallery/')),
                ('page', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.about')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='content/document/')),
                ('title', models.CharField(blank=True, default='Название документа', max_length=30, null=True)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.about')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('link_comm_site', models.URLField()),
                ('map', models.URLField()),
                ('FIO', models.CharField(max_length=130, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='content.seo')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/block')),
                ('main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.main')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
        migrations.CreateModel(
            name='AdditionalGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/additional-gallery/')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.about')),
            ],
            options={
                'verbose_name': 'Дополнительная Галерея',
                'verbose_name_plural': 'Доплонительные Галереи',
            },
        ),
        migrations.AddField(
            model_name='aboutservice',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.seo'),
        ),
        migrations.AddField(
            model_name='about',
            name='seo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='content.seo'),
        ),
    ]
