# Generated by Django 4.1 on 2022-09-16 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_aboutservice_seo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='service',
        ),
        migrations.AddField(
            model_name='aboutservice',
            name='service_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.servicepage'),
        ),
    ]
