# Generated by Django 4.1 on 2022-09-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_contacts_email_alter_contacts_link_comm_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='map',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
