# Generated by Django 4.1 on 2022-11-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_contacts_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
