# Generated by Django 4.1 on 2022-09-10 08:15

import crm_accounting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=crm_accounting.models.get_next_invoice, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('personal_account', models.CharField(max_length=50)),
                ('owner', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_state', models.BooleanField(verbose_name='Проведена')),
                ('status', models.CharField(choices=[('Оплачена', 'Оплачена'), ('Частично оплачена', 'Частично оплачена'), ('Неоплачена', 'Неоплачена')], max_length=120)),
                ('period_start', models.DateField(auto_now_add=True)),
                ('period_end', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Квитанция',
                'verbose_name_plural': 'Квитанции',
            },
        ),
        migrations.CreateModel(
            name='InvoiceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Квитанция с услугами',
                'verbose_name_plural': 'Квитанции с услугами',
            },
        ),
        migrations.CreateModel(
            name='PersonalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(default=crm_accounting.models.get_next_account, unique=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Активен'), ('nonactive', 'Неактивен')], max_length=20, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Персональный счет',
                'verbose_name_plural': 'Персональные счета',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=crm_accounting.models.get_next_transaction)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('completed', models.BooleanField(null=True)),
                ('comment', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
