# Generated by Django 4.1 on 2022-09-10 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0001_initial'),
        ('crm_home', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_home.paymentstate'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='personal_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_accounting.personalaccount'),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='flat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.flat'),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.house'),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.section'),
        ),
        migrations.AddField(
            model_name='invoiceservice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_accounting.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_home.service'),
        ),
        migrations.AddField(
            model_name='invoiceservice',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_home.unit'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.flat'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.section'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_home.tariff'),
        ),
    ]
