# Generated by Django 4.1 on 2022-09-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounting', '0003_remove_personalaccount_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
