# Generated by Django 4.1 on 2022-09-29 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm_accounting', '0004_alter_personalaccount_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalaccount',
            name='phone',
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
