# Generated by Django 4.1 on 2022-09-29 10:10

import crm_accounting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounting', '0005_remove_personalaccount_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='account_number',
            field=models.CharField(default=crm_accounting.models.get_next_account, max_length=14, unique=True),
        ),
    ]
