# Generated by Django 4.1 on 2022-10-13 07:06

import crm_accounting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounting', '0008_remove_personalaccount_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(default=crm_accounting.models.get_next_transaction, max_length=15),
        ),
    ]
