# Generated by Django 4.1 on 2022-10-16 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounting', '0010_alter_transaction_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='phone',
        ),
    ]
