# Generated by Django 4.1 on 2022-10-16 02:12

import crm_accounting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounting', '0011_remove_invoice_owner_remove_invoice_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(default=crm_accounting.models.get_next_invoice, max_length=15, unique=True),
        ),
    ]
