# Generated by Django 4.1 on 2022-10-16 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounting', '0012_alter_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='period_end',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='period_start',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
