# Generated by Django 4.1 on 2022-10-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounting', '0014_remove_invoiceservice_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Выберите...'), ('Оплачена', 'Оплачена'), ('Частично оплачена', 'Частично оплачена'), ('Неоплачена', 'Неоплачена')], max_length=120, null=True),
        ),
    ]
