# Generated by Django 4.1 on 2022-10-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounting', '0015_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Выберите...'), ('Оплачена', 'Оплачена'), ('Частично оплачена', 'Частично оплачена'), ('Неоплачена', 'Неоплачена')], default='Неоплачена', max_length=120, null=True),
        ),
    ]
