# Generated by Django 4.1 on 2022-10-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounting', '0017_alter_invoiceservice_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceservice',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceservice',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
