# Generated by Django 4.1 on 2022-10-26 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_home', '0017_alter_paymentstate_type'),
        ('crm_accounting', '0018_alter_invoiceservice_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceservice',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_accounting.invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_home.service'),
        ),
    ]
