# Generated by Django 4.1 on 2022-11-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounting', '0021_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='templates_invoice/'),
        ),
    ]
