# Generated by Django 4.1 on 2022-11-12 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0014_alter_flat_personal_account'),
        ('crm_accounting', '0023_alter_transaction_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.section'),
        ),
    ]
